# Generated by Django 5.2.1 on 2025-05-28 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOS_Tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
