# Generated by Django 5.2.1 on 2025-05-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SOS_Tracker', '0002_alter_location_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='timestamp',
            new_name='ping_time',
        ),
    ]
