# Generated by Django 5.2.1 on 2025-05-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOS_Tracker', '0003_rename_timestamp_location_ping_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigment_status',
            field=models.BooleanField(default=False),
        ),
    ]
