# Generated by Django 5.2.1 on 2025-05-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SOS_Tracker', '0004_device_assigment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.CharField(default='owo', max_length=40),
            preserve_default=False,
        ),
    ]
